/* Generated by hooks/regen-tracker-dashboard.sh. Do not edit.
   Empty seed state — populated on first edit of tracker.yaml / specs / plans / lessons. */
window.SIGNALS = {
  "generated_at": null,
  "rework": {
    "specs": [],
    "plans": []
  },
  "lessons": {
    "weekly": [],
    "undated_total": 0
  }
};
