/* Generated by hooks/regen-tracker-dashboard.sh. Do not edit.
   Empty seed state — populated on first edit of tracker.yaml / lessons.
   Bugs + Rework are browser-computed from window.TRACKER (no rework key here). */
window.SIGNALS = {
  "generated_at": null,
  "lessons": {
    "weekly": [],
    "undated_total": 0
  }
};
